# Simple Linear Regression

# Importing the dataset
dataset = read.csv('Salary_Data.csv')

# Splitting the dataset into the Training set and Test set
# install.packages('caTools')
library(caTools)
set.seed(123)
split = sample.split(dataset$Salary, SplitRatio = 2/3)
training_set = subset(dataset, split == TRUE)
test_set = subset(dataset, split == FALSE)

# Feature Scaling
# training_set = scale(training_set)
# test_set = scale(test_set)
# simple linear package of R take cares of feature scaling, does not require feature scaling seperately

# fitting simple linear Regressor to the training set.
regressor = lm(formula = Salary ~ YearsExperience , data = training_set)

# summary(regressor) we will see the coefficients of the equation generated by linear model after fitting.
# stars represent the significance of variable statistically , more stars more stastical significance.
# less the p value , more significant of variable it means more impact of independent variable on dependent variable.
# usual threshold for p value is 5. if p value is less then 5 then idependent variable is highly affecting the depending variable.

# predicting the test set result.
y_pred = predict(regressor,newdata = test_set)

# visualizing the training set result.
library('ggplot2')
ggplot() +
  geom_point(aes(x = training_set$YearsExperience, y = training_set$Salary),
             colour = 'red') +
  geom_line(aes(x = training_set$YearsExperience , y = predict(regressor,newdata = training_set))
            ,colour = 'blue') +
  ggtitle('Salary Vs Experience (Training set)') +
  xlab('Years Of Experience') +
  ylab('Salary')

# visualizing the test set result.
ggplot() +
  geom_point(aes(x = test_set$YearsExperience, y = test_set$Salary),
             colour = 'red') +
  geom_line(aes(x = training_set$YearsExperience , y = predict(regressor,newdata = training_set))
            ,colour = 'blue') +
  ggtitle('Salary Vs Experience (Test set)') +
  xlab('Years Of Experience') +
  ylab('Salary')



